# Generated by Django 4.2.3 on 2023-08-09 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
        ('film', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='spectator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie_spectator_ticket', to=settings.AUTH_USER_MODEL, verbose_name='Spectator'),
        ),
        migrations.AddField(
            model_name='session',
            name='one_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.scheduleday', verbose_name='One session'),
        ),
        migrations.AddField(
            model_name='seat',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.session'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.hall'),
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.release', verbose_name='Release'),
        ),
        migrations.AddField(
            model_name='release',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'seat')},
        ),
    ]
