# Generated by Django 4.2.3 on 2023-08-11 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film', '0002_initial'),
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='spectator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.release'),
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie.hall'),
        ),
        migrations.AddField(
            model_name='release',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.hall'),
        ),
        migrations.AddField(
            model_name='release',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'col', 'hall')},
        ),
    ]
