# Generated by Django 4.2.3 on 2023-08-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last_name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth_date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, upload_to='img/actors/', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Comment')),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last_name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth_date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, upload_to='img/directors/', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('poster', models.ImageField(upload_to='img/movies/', verbose_name='Posters')),
                ('running_time', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Running time')),
                ('trailer', models.URLField(blank=True, default='')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('age_rating', models.IntegerField(choices=[(1, '21+'), (2, '18+'), (3, '16+'), (4, '12+'), (5, '6+')])),
                ('actors', models.ManyToManyField(related_name='film_actor', to='film.actor', verbose_name='Actors')),
                ('country', models.ManyToManyField(to='film.country', verbose_name='Countries')),
                ('directors', models.ManyToManyField(related_name='film_director', to='film.director', verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('photo', models.ImageField(blank=True, upload_to='img/film_shots/', verbose_name='Image')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Photo gallery',
                'verbose_name_plural': 'Photo gallery',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='film.genre', verbose_name='Genres'),
        ),
    ]
